### ISSUE TITLE
No module named interactions.decor

### ISSUE THREAD

**Issue by snvmk** [interactions-py/enhanced#10]
When i run my bot that uses Enhanced extension, it says:

```
Traceback (most recent call last):
  File "/home/pi/nernov/main.py", line 7, in <module>
    from interactions.ext.enhanced import (
  File "/home/pi/.venvs/nernov/lib/python3.10/site-packages/interactions/ext/enhanced/__init__.py", line 1, in <module>
    from . import (
  File "/home/pi/.venvs/nernov/lib/python3.10/site-packages/interactions/ext/enhanced/subcommands.py", line 4, in <module>
    from interactions.decor import command
ModuleNotFoundError: No module named 'interactions.decor'
```
How can I install this? Also, previously, it said that there is no colorama, but i installed it, and now this one comes up

**Comment by V3ntus** [comment]
Can be resolved by installing it by this method:
```
pip install git+https://github.com/interactions-py/enhanced
```

**Comment by snvmk** [comment]
have already done that, worked, closing
