### ISSUE TITLE
Error passing kwargs to `EnhancedOption` when used with the `Annotated` type hint

### ISSUE THREAD

**Issue by ShajeshJ** [interactions-py/enhanced#11]
- **Environment**
  `interactions-py` version: 4.3.0
  `enhanced` version: 4.0.0 (commit `9b3631cd4d2b491d0e40763c07b1338264e29458`)
  Python version: 3.10.5
  OS: Ubuntu 20.0.4 WSL 2 subsystem on Windows 10

- **Relevant stack trace**
  ```
  Traceback (most recent call last):
    ...
    File ".../site-packages/interactions/ext/enhanced/commands.py", line 47, in setup_options
      options = parameters_to_options(coro)
    File ".../site-packages/interactions/ext/enhanced/command_models.py", line 172, in parameters_to_options
      _options = [
    File ".../site-packages/interactions/ext/enhanced/command_models.py", line 186, in <listcomp>
      **{key: value for key, value in get_option(param).kwargs},
    File ".../site-packages/interactions/ext/enhanced/command_models.py", line 186, in <dictcomp>
      **{key: value for key, value in get_option(param).kwargs},
  ValueError: too many values to unpack (expected 2)
  ```
  Looks like it might just be a small mistake in how kwargs are unpacked from the `EnhancedOption` object in the `setup_options` decorator

- **Reproduction Code**
  ```python
  import interactions
  import interactions.ext.enhanced as enhanced
  import typing
  
  bot = interactions.Client("<token>")
  
  command_choices = [interactions.Choice(name="Option 1", value="option_1")]
  
  @bot.command()
  @enhanced.setup_options
  async def command(
      ctx: interactions.CommandContext,
      opt: typing.Annotated[
          str,
          enhanced.EnhancedOption(str, description="some desc", choices=command_choices),
      ]
  ):
      """Command desc"""
      pass
  ```

- **Expected Behaviour**
  `Option` created with the command is passed any additional kwargs given to `EnhancedOption` (i.e. `choices` in the sample code)

**Comment by Toricane** [comment]
Thank you, i will try to fix this asap

**Comment by Toricane** [comment]
Sorry for the delay, looks like I didn't test options with choices.
I will fix this now, thanks.

**Comment by Toricane** [comment]
Fixed, thank you!

**Comment by ShajeshJ** [comment]
Awesome, thank you for the fix 🙏
